spring.application.name=SoundCloudClone
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

server.port=8080
# Cloudinary
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:your-cloud-name}
cloudinary.api-key=${CLOUDINARY_API_KEY:your-api-key}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:your-api-secret}


# JPA
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
spring.jackson.time-zone=GMT+7

jwt.secret_key=za7RBDP39Dd+eRmC0hvQijh+D4LzmEXBqAjJsFWIbmrrjYwqkZkR6YRanH9N9E5r

# Debug Spring Security
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.web.FilterChainProxy=DEBUG

# Upload
spring.servlet.multipart.max-file-size=10MB

# Redis config
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Actuator
management.endpoints.web.exposure.include=health,metrics
